export const SAVING_FORM = 'SAVING_FORM';
export const API_CALL_STARTED = 'API_CALL_STARTED';

export const SAVE_FORM_SUCCESS = 'SAVE_FORM_SUCCESS';
export const SAVE_FORM_FAILURE = 'SAVE_FORM_FAILURE';

export const UPDATE_FORM_ATTR = 'UPDATE_FORM_ATTR';
export const UPDATE_FORM_ATTR_HAS_ERRORS = 'UPDATE_FORM_ATTR_HAS_ERRORS';
